controller:
  kind: Deployment
  ingressClass: haproxy
  service:
    type: LoadBalancer
  config:
    ssl-redirect: "true"
    timeout:
      client: "30s"
      connect: "5s"
      http-request: "5s"
      queue: "5s"
      server: "30s"
      tunnel: "3h"
  logging:
    level: info
