name: Setup Environment
description: Install dependencies for the monorepo and cache it

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      shell: bash
    - uses: actions/setup-node@v4
      shell: bash
      with:
        node-version: 20
        cache: "pnpm"
    - uses: actions/cache@v4
      shell: bash
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
    - run: pnpm install
      shell: bash
