# WARN: should not be used to deploy in production since credentials are in plain text.
# NOTE: Needs to be used in relation to core/compose.yaml
# Should ONLY be used for dev/test environments
# Represents entire infrastructure as a monolith
networks:
  homelab-network:
    external: true
    name: setup_homelab-network

services:
  base:
    image: homelab-base:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development

  web:
    image: homelab-web:latest
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: ".env"
    environment:
      - USER_DB_HOST=userdb
      - MAIN_REDIS_HOST=cache
    depends_on:
      - base
    networks:
      - homelab-network
