# WARN: should not be used to deploy in production since credentials are in plain text.
# NOTE: Needs to be used in relation to core/compose.yaml
# Should ONLY be used for dev/test environments
# Represents entire infrastructure as a monolith
networks:
  homelab-network:
    external: true
    name: setup_homelab-network

services:
  base:
    image: homelab-base:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development

  web:
    image: homelab-web:latest
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - USER_DB_USERNAME=user
      - USER_DB_PASSWORD=password
      - USER_DB_HOST=userdb
      - USER_DB_PORT=5432
      - USER_DB_DATABASE=userdb
      - MAIN_REDIS_PASSWORD=password
      - MAIN_REDIS_HOST=cache
      - MAIN_REDIS_PORT=6379
      - PUBLIC_PROTOCOL=http
      - PUBLIC_DOMAIN=localhost
      - PUBLIC_APP_NAME=homelab-template
    depends_on:
      - base
    networks:
      - homelab-network
