# WARN: should not be used in production since credentials are in plain text.
# Should ONLY be used for dev/test environments
# Represents infrastructure as a monolith
networks:
  homelab-network:
    driver: bridge

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile

  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - USER_DB_USERNAME=user
      - USER_DB_PASSWORD=password
      - USER_DB_HOST=userdb
      - USER_DB_PORT=5432
      - USER_DB_DATABASE=userdb
      - MAIN_REDIS_PASSWORD=password
      - MAIN_REDIS_HOST=cache
      - MAIN_REDIS_PORT=6379
      - PUBLIC_PROTOCOL=http
      - PUBLIC_DOMAIN=localhost:3000
      - PUBLIC_APP_NAME='Homelab Template'
    depends_on:
      - base
      - cache
      - userdb
    networks:
      - homelab-network

  cache:
    image: redis:7-alpine
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    networks:
      - homelab-network

  userdb:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userdb
    networks:
      - homelab-network
