/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "CACert": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CAKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CASerial": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CloudflareApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseBackupBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "HetznerToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainDbAdminPass": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainDbAdminUser": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainDbMasterCert": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainDbMasterKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainDbName": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainDbPoolPass": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainDbRepPass": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainDbSlave1Cert": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainDbSlave1Key": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainRedisPass": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainRedisUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PgBackrestCert": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PgBackrestKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PublicSSHKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
