apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-docker-pool
  namespace: metallb-system
spec:
  addresses:
    # TODO: change this to progammatically set this
    - 172.18.255.200-172.18.255.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertise-local-docker-pool
  namespace: metallb-system
spec:
  ipAddressPools:
    - local-docker-pool
