# Used to setup the core dependencies that most packages will need
networks:
  homelab-network:
    driver: bridge

services:
  cache:
    image: redis:7-alpine
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    networks:
      - homelab-network
    healthcheck:
      test: redis-cli ping
      interval: 1s
      retries: 10

  maindb:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file: "../../.env"
    environment:
      - POSTGRES_DB=main
      - PGDATABASE=main
    volumes:
      - ./src/database/main/setup/0001_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/database/main/setup/0002_roles.sql:/docker-entrypoint-initdb.d/roles.sql
    networks:
      - homelab-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "admin", "-d", "main"]
      interval: 1s
      retries: 10

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  # essentially an empty container that makes sure the previous services are initialized
  ready:
    image: alpine:latest
    depends_on:
      maindb:
        condition: service_healthy
      cache:
        condition: service_healthy
