<script lang="ts">
  import type { ActionData, PageData } from './$types';
  import OtpForm from './otp-form.svelte';

  export let data: PageData;
  export let form: ActionData;

  $: if (form) {
    formInteracted = false;
  }

  let formInteracted = false;
</script>

<div class="h-screen">
  <div class="flex items-center justify-center h-screen">
    <div class="mx-auto grid w-[350px] gap-6">
      <div class="grid gap-2 text-center">
        <h1 class="text-3xl font-bold">One Time Password</h1>
        <p class="text-balance text-muted-foreground">
          Enter the code generated by your authenticator
        </p>
        {#if form && !form.success && !formInteracted}
          <p class="text-balance text-red-600">Invalid Code</p>
        {/if}
      </div>

      <OtpForm on:interacted={() => (formInteracted = true)} data={data.otpForm} />

      <div class="text-center text-sm">
        Don&apos;t have your authenticator?
        <a href="/auth/2fa/recover" class="underline"> Recovery Code </a>
      </div>
    </div>
  </div>
</div>
