apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgbackrest-backup
  namespace: main
spec:
  commonName: pgbackrest-backup.main.svc.cluster.local
  secretName: pgbackrest-backup-tls
  dnsNames:
    - pgbackrest-backup.main.svc.cluster.local
    - pgbackrest-backup
  usages:
    - server auth
    - client auth
  issuerRef:
    name: internal-ca-issuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: patroni-main
  namespace: main
spec:
  commonName: patroni-main-primary.main.svc.cluster.local
  secretName: patroni-main-tls
  dnsNames:
    - patroni-main-primary.main.svc.cluster.local
    - "*.patroni-main-primary.main.svc.cluster.local"
  usages:
    - server auth
    - client auth
  issuerRef:
    name: internal-ca-issuer
