apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - certs.yaml
  - master.yaml
  - slave.yaml
  - pgbackrest.yaml
  - pgcat.yaml
configMapGenerator:
  - name: pgcat-main-config
    files:
      - ../../../packages/postgres/images/pgcat/pgcat.toml
  - name: pgbackrest-main-config
    files:
      - ../../../packages/postgres/images/backup/pgbackrest.conf
  - name: masterdb-main-config
    files:
      - ../../../packages/postgres/images/master/master.sh
      - ../../../packages/postgres/main/setup/0000_init.sql
      - ../../../packages/postgres/main/setup/0001_roles.sql
      - ../../../packages/postgres/main/setup/0002_extensions.sql
      - ../../../packages/postgres/main/setup/0003_cron.sql
  - name: postgres-main-config
    files:
      - ../../../packages/postgres/images/pgbackrest.conf
      - ../../../packages/postgres/images/postgresql.conf
      - ../../../packages/postgres/images/pg_hba.conf
generatorOptions:
  disableNameSuffixHash: false # changes the suffix hash of names so services automatically reload
