apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - master.yaml
  - slave.yaml
  - pgcat.yaml
  - pgbackrest.yaml
  - pvcs.yaml
  - configmaps.yaml

images:
  - name: masterdb
    newName: masterdb
    newTag: latest
  - name: slavedb
    newName: slavedb
    newTag: latest
  - name: pooler
    newName: pooler
    newTag: latest
  - name: backup
    newName: backup
    newTag: latest