apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: patroni-main
  namespace: main
  labels:
    app: &app patroni-main
    cluster-name: &cluster-name main
spec:
  replicas: 3
  serviceName: patroni-main-primary
  selector:
    matchLabels:
      app: *app
      cluster-name: *cluster-name
  template:
    metadata:
      labels:
        app: *app
        cluster-name: *cluster-name
    spec:
      serviceAccountName: patroni-main
      securityContext:
        fsGroup: 999
      # if you are trying to restore an existing backup to patroni, make sure to delete the PVC bound to it
      containers:
        - name: *app
          image: local-registry:12345/patroni:latest
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /readiness
              port: 8008
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8008
              protocol: TCP
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: main
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MAIN_ENCRYPTION_KEY
              value: openssl-rand-hex-32
          volumeMounts:
            - name: patroni-config
              mountPath: /tmp/conf_templates/pgbackrest.conf
              subPath: pgbackrest.conf
            - name: patroni-config
              mountPath: /tmp/conf_templates/patroni.yaml
              subPath: patroni.yaml
            - name: pgbackrest-ca
              mountPath: /etc/pgbackrest/ca.crt
              subPath: tls.crt
            - name: pgbackrest-server-tls
              mountPath: /etc/pgbackrest/server.crt
              subPath: tls.crt
            - name: pgbackrest-server-tls
              mountPath: /etc/pgbackrest/server.key
              subPath: tls.key
            - name: patroni-main-tls
              mountPath: /etc/pgbackrest/client.crt
              subPath: tls.crt
            - name: patroni-main-tls
              mountPath: /etc/pgbackrest/client.key
              subPath: tls.key
            - name: patroni-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: pgbackrest-ca
          secret:
            secretName: internal-root-ca-secret
            defaultMode: 0600
        - name: pgbackrest-server-tls
          secret:
            secretName: pgbackrest-backup-tls
            defaultMode: 0600
        - name: patroni-main-tls
          secret:
            secretName: patroni-main-tls
            defaultMode: 0600
        - name: patroni-config
          configMap:
            name: patroni-config
  volumeClaimTemplates:
    - metadata:
        name: patroni-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi

---
# provides a stable ip for the primary
apiVersion: v1
kind: Service
metadata:
  name: patroni-main-primary
  namespace: main
  labels:
    app: &app patroni-main
    cluster-name: &cluster-name main
    role: &role primary
spec:
  type: ClusterIP
  selector:
    app: *app
    cluster-name: *cluster-name
    role: *role
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: pgbackrest
      port: 8432
      targetPort: 8432

---
# provides a stable ip for all replicas
apiVersion: v1
kind: Service
metadata:
  name: patroni-main-replica
  namespace: main
  labels:
    app: &app patroni-main
    cluster-name: &cluster-name main
    role: &role replica
spec:
  type: ClusterIP
  selector:
    app: *app
    cluster-name: *cluster-name
    role: *role
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: pgbackrest
      port: 8432
      targetPort: 8432

---
# ---- below are permissions that patroni needs to get access to k8s API ----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patroni-main
  namespace: main

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patroni-main
  namespace: main
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - patch
      - update
      - create
      - list
      - watch
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patroni-main
  namespace: main
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patroni-main
subjects:
  - kind: ServiceAccount
    name: patroni-main
    namespace: main
