apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbackrest-backup
  namespace: main
  labels:
    app: pg-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-backup
  template:
    metadata:
      labels:
        app: pg-backup
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: pg-backup
          image: local-registry:12345/backup:latest
          env:
            - name: POSTGRES_DB_1
              value: main
            - name: MASTER_HOST_1
              value: masterdb-1
            - name: SLAVE_HOST1_1
              value: slavedb-1
            - name: MAIN_ENCRYPTION_KEY
              value: openssl-rand-hex-32
          volumeMounts:
            - name: pgbackrest-ca-cert
              mountPath: /etc/pgbackrest/ca.crt
              subPath: tls.crt
            - name: pgbackrest-server-tls
              mountPath: /etc/pgbackrest/server.crt
              subPath: tls.crt
            - name: pgbackrest-server-tls
              mountPath: /etc/pgbackrest/server.key
              subPath: tls.key
            - name: pgbackrest-conf
              mountPath: /tmp/conf_templates/pgbackrest.conf
              subPath: pgbackrest.conf
              readOnly: true
      volumes:
        - name: pgbackrest-ca-cert
          secret:
            secretName: internal-root-ca-secret
            defaultMode: 0600
        - name: pgbackrest-server-tls
          secret:
            secretName: pgbackrest-backup-tls
            defaultMode: 0600
        - name: pgbackrest-conf
          configMap:
            name: pgbackrest-server-config
