apiVersion: v1
kind: Service
metadata:
  name: main-database
  namespace: main
  labels:
    app: &app pgcat-main
spec:
  ports:
    - port: 6432
      targetPort: 6432
  selector:
    app: *app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgcat-main-pooler
  namespace: main
  labels:
    app: &app pgcat-main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - name: *app
          image: local-registry:12345/pgcat:latest
          env:
            - name: POSTGRES_DB
              value: main
            - name: POSTGRES_USER
              value: pgcat
            - name: MASTER_HOST_1
              value: patroni-main-primary.main.svc.cluster.local
            - name: SLAVE_HOST_1
              value: patroni-main-replica.main.svc.cluster.local
          volumeMounts:
            - name: pgcat-conf
              mountPath: /tmp/conf_templates/pgcat.toml
              subPath: pgcat.toml
              readOnly: true
      volumes:
        - name: pgcat-conf
          configMap:
            name: pgcat-main-config
