apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgcat-pooler
  namespace: main
  labels:
    app: pgcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgcat
  template:
    metadata:
      labels:
        app: pgcat
    spec:
      containers:
        - name: pgcat
          image: local-registry:12345/pooler:latest
