apiVersion: v1
kind: Service
metadata:
  name: slavedb
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-slave

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-slave
spec:
  selector:
    matchLabels:
      app: postgres-slave
  template:
    metadata:
      labels:
        app: postgres-slave
    spec:
      containers:
        - name: postgres-slave
          image: ${REGISTRY_URL:+${REGISTRY_URL}/}slavedb:${SLAVEDB_TAG:-latest}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: main
            - name: PGDATABASE
              value: main
            - name: POSTGRES_TYPE
              value: backup
            - name: MASTER_HOST
              value: postgres-master
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-conf
              mountPath: /tmp/conf_templates/postgresql.conf
              subPath: postgresql.conf
            - name: pg-hba-conf
              mountPath: /tmp/conf_templates/pg_hba.conf
              subPath: pg_hba.conf
            - name: pgbackrest-conf
              mountPath: /tmp/conf_templates/pgbackrest.conf
              subPath: pgbackrest.conf
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "admin", "-d", "main"]
            initialDelaySeconds: 5
            periodSeconds: 1
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "admin", "-d", "main"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgresql-conf
          configMap:
            name: postgres-config
        - name: pg-hba-conf
          configMap:
            name: postgres-config
        - name: pgbackrest-conf
          configMap:
            name: postgres-config
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-slave-data