apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slavedb-main-1
  namespace: main
  labels:
    app: slavedb-main-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slavedb-main-1
  template:
    metadata:
      labels:
        app: slavedb-main-1
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: slavedb-main-1
          image: local-registry:12345/slavedb:latest
          env:
            - name: POSTGRES_DB
              value: main
            - name: PGDATABASE
              value: main
            - name: POSTGRES_TYPE
              value: backup
            - name: MASTER_HOST
              value: masterdb-1
          volumeMounts:
            - name: postgres-main-config
              mountPath: /tmp/conf_templates/postgresql.conf
              subPath: postgresql.conf
            - name: postgres-main-config
              mountPath: /tmp/conf_templates/pg_hba.conf
              subPath: pg_hba.conf
            - name: slavedb-main-config
              mountPath: /tmp/conf_templates/pgbackrest.conf
              subPath: pgbackrest.conf
            - name: slavedb-ca-cert
              mountPath: /etc/pgbackrest/ca.crt
              subPath: tls.crt
            - name: pgbackrest-server-tls
              mountPath: /etc/pgbackrest/server.crt
              subPath: tls.crt
            - name: pgbackrest-server-tls
              mountPath: /etc/pgbackrest/server.key
              subPath: tls.key
            - name: slavedb-client-tls
              mountPath: /etc/pgbackrest/client.crt
              subPath: tls.crt
            - name: slavedb-client-tls
              mountPath: /etc/pgbackrest/client.key
              subPath: tls.key
      volumes:
        - name: slavedb-main-config
          configMap:
            name: slavedb-main-config
        - name: postgres-main-config
          configMap:
            name: postgres-main-config
        - name: slavedb-ca-cert
          secret:
            secretName: internal-root-ca-secret
            defaultMode: 0600
        - name: pgbackrest-server-tls
          secret:
            secretName: pgbackrest-backup-tls
            defaultMode: 0600
        - name: slavedb-client-tls
          secret:
            secretName: slavedb-main-1-tls
            defaultMode: 0600
  volumeClaimTemplates:
    - metadata:
        name: slavedb-main-1-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
