# https://raw.githubusercontent.com/valkey-io/valkey/8.1/valkey.conf
protected-mode no
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-allow-reads-when-down yes
cluster-announce-port 6379
cluster-announce-bus-port 16379
cluster-announce-ip ${POD_IP}
replica-announce-ip ${POD_IP}
stop-writes-on-bgsave-error no
port 6379
cluster-port 16379
