<script lang="ts">
  import OtpForm from './otp-form.svelte';

  let { data, form } = $props();

  let formInteracted = $state(false);
  $effect(() => {
    if (form) {
      formInteracted = false;
    }
  });
</script>

<div class="h-screen">
  <div class="flex items-center justify-center h-screen">
    <div class="mx-auto grid w-[350px] gap-6">
      <div class="grid gap-2 text-center">
        <h1 class="text-3xl font-bold">One Time Password</h1>
        <p class="text-balance text-muted-foreground">
          Enter the code generated by your authenticator
        </p>
        {#if form && !form.success && !formInteracted}
          {#if form.throttled}
            <p class="text-balance text-red-600">Too Many Attempts. Try Later.</p>
          {:else}
            <p class="text-balance text-red-600">Invalid Code</p>
          {/if}
        {/if}
      </div>

      <OtpForm interacted={() => (formInteracted = true)} data={data.otpForm} />

      <div class="text-center text-sm">
        Don&apos;t have your authenticator?
        <a href="/auth/2fa/recover" class="underline"> Recovery Code </a>
      </div>
    </div>
  </div>
</div>
