#!/bin/sh

psql -c "CREATE USER replicator WITH REPLICATION LOGIN ENCRYPTED PASSWORD '$PGREPPASS'"

psql -c "CREATE USER pooler WITH PASSWORD '$PGPOOLPASS'"
psql -c "GRANT CONNECT TO DATABASE $POSTGRES_DB to pooler"
psql -c "GRANT USAGE ON SCHEMA public TO pooler"
psql -c "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pooler"
psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pooler"
