#!/bin/sh

psql -c "CREATE USER replicator WITH REPLICATION LOGIN ENCRYPTED PASSWORD '$(echo $PGREPPASS)'"
psql -c "CREATE USER pooler WITH PASSWORD '$(echo $PGPOOLPASS)'"
psql -c "GRANT ALL PRIVILEGES ON DATABASE $(echo $POSTGRES_DB) TO pooler"
