services:
  backup:
    image: ${REGISTRY_URL:+${REGISTRY_URL}/}backup:${BACKUP_TAG:-latest}
    build:
      context: ./backup

  pgcat:
    image: ${REGISTRY_URL:+${REGISTRY_URL}/}pgcat:${PGCAT_TAG:-latest}
    build:
      context: ./pgcat

  patroni:
    image: ${REGISTRY_URL:+${REGISTRY_URL}/}patroni:${PATRONI_TAG:-latest}
    build:
      context: ./patroni
