apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - ../base/web.yaml
  - ../base/postgres/pgbackrest.yaml
  - ../base/postgres/pooler.yaml
configMapGenerator:
  - name: env
    envs:
      - ../../.env
patches:
  - path: env-patch.yaml
