apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - ../base/web.yaml
  - ../base/postgres/pgbackrest.yaml
  - ../base/postgres/pooler.yaml
secretGenerator:
  - name: env
    envs:
      - ../../.env
generatorOptions:
  disableNameSuffixHash: false # changes the suffix hash of names so services automatically reload
patches:
  - path: env-patch.yaml
