apiVersion: v1
kind: Service
metadata:
  name: s3
  namespace: main
spec:
  selector:
    app: s3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
  namespace: main
spec:
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app: s3
    spec:
      containers:
        - name: s3
          image: localstack/localstack
          env:
            - name: SERVICES
              value: s3
            - name: AWS_DEFAULT_REGION
              value: us-west-1
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: testsecret
