apiVersion: v1
kind: Service
metadata:
  name: s3
  namespace: main
spec:
  selector:
    app: s3
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-init-script
  namespace: main
data:
  s3.sh: |
    #!/bin/sh
    awslocal s3 mb s3://$(echo $BACKUP_BUCKET)

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: s3
  namespace: main
spec:
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app: s3
    spec:
      containers:
        - name: s3
          image: localstack/localstack
          envFrom:
            - secretRef:
                name: env
          env:
            - name: SERVICES
              value: s3
            - name: AWS_DEFAULT_REGION
              value: us-west-1
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: testsecret
          volumeMounts:
            - name: init-script
              mountPath: /etc/localstack/init/ready.d/s3.sh
              subPath: s3.sh
            - name: s3-data
              mountPath: /var/lib/localstack
      volumes:
        - name: init-script
          configMap:
            name: s3-init-script
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: s3-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
