name: Docker

on:
  push:
    branches:
      - main
      - dev

jobs:
  base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/pandoks/base

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: echo "BASE_IMAGE=${{ steps.meta.outputs.tags }}" >> $GITHUB_OUTPUT

  builds:
    runs-on: ubuntu-latest
    needs: base
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - web

    steps:
      - run: echo ${{ needs.base.outputs }}
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/pandoks/${{ matrix.image }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./packages/${{ matrix.image }}
          file: ./packages/${{ matrix.image }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE=${{ env.BASE_IMAGE }}
