name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Setup:
    uses: .github/workflows/setup.yaml

  Docker:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Build Docker Images
        run: docker build .
