name: Docker

on:
  push:
    branches:
      - main
      - dev

jobs:
  base:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/pandoks/base:0.0.0.0
          cache-from: type=registry,ref=pandoks/base:buildcache
          cache-to: type=registry,ref=pandoks/base:buildcache,mode=max

  builds:
    runs-on: ubuntu-latest
    needs: base
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - web

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./packages/${{ matrix.image }}
          file: ./Dockerfile
          push: true
          tags: ghcr.io/pandoks/${{ matrix.image}}:0.0.0.0
          cache-from: type=registry,ref=pandoks/${{ matrix.image }}:buildcache
          cache-to: type=registry,ref=pandoks/${{ matrix.image }}:buildcache,mode=max
          build-args: |
            BASE: ghcr.io/pandoks/base:latest
