name: Test Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - core
          - web

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run unit tests
        run: |
          cd packages/${{ matrix.package }}
          pnpm run test:unit
  no-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - core
          - web

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
      - run: pnpm install
      - uses: ./.github/actions/setup
      - name: Run unit tests
        run: |
          cd packages/${{ matrix.package }}
          pnpm run test:unit
