name: Test Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - core
          - web

    steps:
      - uses: actions/checkout@v4

      - name: Use caches and install dependencies if needed
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: |
          cd packages/${{ matrix.package }}
          pnpm run test:unit

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - web

    steps:
      - uses: actions/checkout@v4

      - name: Use caches and install dependencies if needed
        uses: ./.github/actions/setup

      - name: Run integration tests
        run: |
          cd packages/${{ matrix.package }}
          pnpm run test:int
