name: Test Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  Setup:
    uses: ./.github/workflows/setup.yaml

  Unit-Tests:
    runs-on: ubuntu-latest
    needs: Setup
    strategy:
      matrix:
        package:
          - core
          - web

    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          cd packages/${{ matrix.package }}
          pnpm run test:unit
